### ISSUE TITLE
Value Error on Blender 4.2 with internal Python 3.11.7

### ISSUE THREAD

**Issue by Alpha1972m** [walkoncross/blender_bvh_addon_enhanced#2]
I'm getting an Value Error : invalid mode: 'rU' when iporting a bhv. 

Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_anim_bvh_enhanced\__init__.py", line 214, in execute
    return import_bvh_enhanced.load(context, report=self.report, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_anim_bvh_enhanced\import_bvh_enhanced.py", line 1075, in load
    bvh_nodes, bvh_frame_time, bvh_frame_count = read_bvh(
                                                 ^^^^^^^^^
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_anim_bvh_enhanced\import_bvh_enhanced.py", line 121, in read_bvh
    file = open(file_path, 'rU')
           ^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'

**Comment by zaher** [comment]
I fixed it in my fork https://github.com/zaher/blender_bvh_addon_enhanced/
